[package]
name = "wt_penetration_tool"
version = "0.0.2"
authors = ["FlareFlo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
inputbot = "0.5.0"
captrs = "0.3.1"
image = "0.23.14"
scrap = "0.5.0"