[package]
name = "wt_penetration_tool"
version = "0.1.0"
authors = ["FlareFlo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
inputbot = "0.5.0"